#ifndef __LIBSGM_CONFIG_H__
#define __LIBSGM_CONFIG_H__

/* #undef LIBSGM_SHARED */

#define LIBSGM_VERSION 
#define LIBSGM_VERSION_MAJOR 
#define LIBSGM_VERSION_MINOR 
#define LIBSGM_VERSION_PATCH 

/* #undef BUILD_OPENCV_WRAPPER */

#endif // __LIBSGM_CONFIG_H__
