#ifndef _FTL_NET_PROTOCOL_HPP_
#define _FTL_NET_PROTOCOL_HPP_

#define FTL_PROTOCOL_HS1		0x0001		// Handshake step 1
#define FTL_PROTOCOL_HS2		0x0002		// Handshake step 2

#define FTL_PROTOCOL_RPC		0x0100
#define FTL_PROTOCOL_RPCRETURN	0x0101

#define FTL_PROTOCOL_P2P		0x1000

#endif // _FTL_NET_PROTOCOL_HPP_
